### ISSUE TITLE
Secret Option Require to access

### ISSUE THREAD

**Issue by aadityaagrawal** [riad-azz/instagram-video-downloader#1]
When opening your hosted site, https://insta-vids-downloder.riadazzoun.repl.co/  it is showing {"error":"secret option required for sessions"}

**Comment by riad-azz** [comment]
Thanks it was fixed, replit deleted my .env without saving the enviroment variables as secrets.
Now its live and working.

**Comment by aadityaagrawal** [comment]
Also, I wanted to make this for a mobile application. I just wanted to ask if it is legit to get/download videos from Instagram or YouTube and What could be done?
Do we need to get this API from somewhere or do we need to make it ourselves?

**Comment by riad-azz** [comment]
If you are talking about license the API is fully mine, it just scrapes the instagram post  page and fetches the mp4 link, and yeah you can use it in your application.
Just host it somewhere, remove the index route and add a access_key  key to the `/api` route and you should be good.
But if you are talking about if its legit to download instagram videos you will have to check their Terms of service.

**Comment by aadityaagrawal** [comment]
Thank You So Much @riad-azz for your help. It means a lot.
