### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by elegance666** [riad-azz/instagram-video-downloader#18]
npm run build

> instagram-videos-downloader@1.0.0 build
> next build

  ▲ Next.js 14.2.16
  - Environments: .env

   Creating an optimized production build ...
Failed to compile.

./src/app/layout.tsx
Module not found: Can't resolve '@/components/navbar'

https://nextjs.org/docs/messages/module-not-found

./src/app/layout.tsx
Module not found: Can't resolve '@/components/footer'

https://nextjs.org/docs/messages/module-not-found

**Comment by elegance666** [comment]
✓ Starting...
 ⚠ Found lockfile missing swc dependencies, patching...
 ✓ Ready in 2.9s
 ⚠ Lockfile was successfully patched, please run "npm install" to ensure @next/swc dependencies are downloaded
 ○ Compiling /_not-found ...
 ⨯ ./src/app/layout.tsx:6:1
Module not found: Can't resolve '@/components/navbar'
  4 | import "@/styles/globals.css";
  5 |
> 6 | import { Navbar } from "@/components/navbar";
    | ^
  7 | import { Footer } from "@/components/footer";
  8 |
  9 | import { ThemeProvider } from "@/components/providers/theme-provider";

https://nextjs.org/docs/messages/module-not-found
 ✓ Compiled /_not-found in 435ms (286 modules)
 ○ Compiling / ...
 ⨯ ./src/app/layout.tsx:6:1
Module not found: Can't resolve '@/components/navbar'
  4 | import "@/styles/globals.css";
  5 |
> 6 | import { Navbar } from "@/components/navbar";
    | ^
  7 | import { Footer } from "@/components/footer";
  8 |
  9 | import { ThemeProvider } from "@/components/providers/theme-provider";

https://nextjs.org/docs/messages/module-not-found
 GET / 500 in 295ms

**Comment by riad-azz** [comment]
Thank you for reporting this issue

There was a problem in the file name where the files `navbar.tsx` and `footer.tsx` had lower case first letter but on the repository they had upper first letter `Navbar.tsx` & `Footer.tsx` which was causing the import error.

This has been fixed with : https://github.com/riad-azz/instagram-video-downloader/commit/aebb898ea9477d36762a43b975f4a49784c9fe38

have a great day
