### ISSUE TITLE
Please add image support.

### ISSUE THREAD

**Issue by ruizlenato** [riad-azz/instagram-video-downloader#3]
![image](https://github.com/riad-azz/instagram-video-downloader/assets/49354525/2038a29a-6bde-4887-ad56-d8be59462d0d)

**Comment by riad-azz** [comment]
Thanks for the suggestion however, the focus of this website is solely on downloading videos, maybe in the future i make another repository for a full Instagram saver but I don't plan to add image support on this one. Sorry for any inconvenience, and thanks for understanding.
