### ISSUE TITLE
This post is private or does not exist False error

### ISSUE THREAD

**Issue by abdu558** [riad-azz/instagram-video-downloader#8]
**Describe the bug**
This post is private or does not exist even though the post is valid and can be viewed normally on any account.
such as: This post is private or does not exist

**To Reproduce**

This happens in the website and the cloned app

1. Sumbit this link https://www.instagram.com/p/Cyy9LKZNYr_/
2. See error
3. Open the link on instagram and it works fine

**Expected behavior**
I expected it to work normally, but the error comes up. It should download it, I dont understand why this happens as i ran over 100 posts and 2 got flagged for this error.

**Comment by riad-azz** [comment]
The problem had to do with a check in an attempt for better performance in `src/lib/instagram/scrapers/webpage.ts` :

```js
  if (!response.data.includes('hreflang="x-default"')) {
    throw new BadRequest("This post is private or does not exist");
  }
```

Issue has been fixed with the latest commit.
